---
builds:
  - type: go
    id: build
    ldflags: "-s -w -X main.version={{.Version}}"
    main: ./cmd/sensu-influx-handler-server
    output: "{{.ProjectName}}-{{.Version}}-{{.OS}}-{{.Arch}}{{.Ext}}"
    goos:
      - linux
      - windows
    goarch:
      - amd64
    before:
      - go mod tidy
archives:
  - type: changelog
    id: changelog
  - type: upx
    builds:
      - build
publishes:
  - type: github
    builds:
      - build
    owner: julian7
    name: sensu-influx-handler-server
    release_notes: changelog
